# Generated by Django 4.0.4 on 2022-04-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('prep_time', models.IntegerField()),
                ('posted_by', models.CharField(max_length=50)),
                ('serves', models.IntegerField()),
                ('ingredients', models.TextField()),
                ('process', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
