# Generated by Django 4.0.4 on 2022-04-23 19:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=cloudinary.models.CloudinaryField(default='image url', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
