# Generated by Django 4.0.4 on 2022-04-23 21:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='process',
            field=tinymce.models.HTMLField(),
        ),
    ]
